export const Config = {
  ONESTEP_CLIENT_TOKEN: '<YOUR_CLIENT_TOKEN>',
  ONESTEP_IDENTITY_SECRET: '<YOUR_IDENTITY_VERIFICATION_SECRET>',
  REVENUECAT_API_KEY: 'YOUR_REVENUECAT_API_KEY',
  DEFAULT_RECORDING_DURATION_MS: 60_000,
  ANALYSIS_TIMEOUT_MS: 60_000,
  WEEKLY_GOAL_SESSIONS: 5,
  DAILY_REMINDER_HOUR: 9,
};
